### ISSUE TITLE
Can't make it work since the latest refactoring

### ISSUE THREAD

**Issue by tetronomis** [cleentfaar/CLSlackBundle#10]
I used the bundle on version 0.12.1 and it worked great.
Today by running a composer update the slack library got upgraded to 0.12.3 and it doesn't work anymore. My symfony silently crashes when instantiating my service with a dependency on cl_slack.api_client.

I have now way to go back to previous setup because the bundle requires "cleentfaar/slack": "~0.12" that fetches refactored slack library.

**Comment by cleentfaar** [comment]
Hi @tetronomis! 

Sad to hear my refactoring last week has caused you some trouble. On the plus side: a lot of these issues got fixed last night, so if you haven't lost faith in this package yet :smile:... here are 2 tips:

- Update this package, it should be fixed for you now.
- Check out the updated [usage documentation](https://github.com/cleentfaar/CLSlackBundle/blob/master/Resources/doc/usage.md), I've added a factory class that reduces the amount of code needed to send payloads. You can still construct the payloads yourself of course, it's just a helper.
- If an issue like that occurs with composer, you can always force composer to use a specifc commit of this package by writing the version like this: 
```json
"requires": {
  "cleentfaar/slack-bundle": "dev-master#a1b2c3d4"
},
```

Hope this helps! 

Ps. If you are still having issues, please also provide the exact error(trace) you get so I can debug it a bit better.

**Comment by tetronomis** [comment]
Hi, thanks a lot for your help.
I've followed all your instructions but now I'm getting this error:
Fatal error: Class 'CL\Slack\Util\PayloadSerializer' not found

The trace:
8	0.8743	10836696	Symfony\Bundle\FrameworkBundle\Controller\Controller->get( )	../ContactController.php:84
9	0.8743	10836696	Symfony\Component\DependencyInjection\Container->get( )	../Controller.php:275
10	0.8743	10837176	appDevDebugProjectContainer->getGf_Services_SlackService( )	../bootstrap.php.cache:2083
11	0.8746	10843376	Symfony\Component\DependencyInjection\Container->get( )	../appDevDebugProjectContainer.php:2508
12	0.8746	10843776	appDevDebugProjectContainer->getClSlack_ApiClientService( )	../bootstrap.php.cache:2083
13	0.8749	10849088	Symfony\Component\DependencyInjection\Container->get( )	../appDevDebugProjectContainer.php:1427
14	0.8749	10849504	appDevDebugProjectContainer->getClSlack_PayloadSerializerService( )	../bootstrap.php.cache:2083

**Comment by cleentfaar** [comment]
Sorry to hear this (again)! More refactorings have been made in the past few days to all related packages. 

I've also added tests to make sure the defined services exist so this issue does not occur again (I hope). 

If you want to give it a (3rd?) chance, adjust your `composer.json` to use version `~0.15.1` and let me know of any further issues of course!

Release: https://github.com/cleentfaar/CLSlackBundle/releases/tag/0.15.1
