### ISSUE TITLE
 Failed to send payload

### ISSUE THREAD

**Issue by antonioperic** [cleentfaar/CLSlackBundle#14]
Hi, I did composer update few days ago and since then I cannot sent my message to slack. Here is error 

Failed to send payload
500 Internal Server Error - SlackException
2 linked Exceptions:

    SlackException » RequestException » 

[3/3] SlackException: Failed to send payload  +
[2/3] SlackException: Failed to send data to the Slack API  +
[1/3] RequestException: cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by titouan13** [comment]
Hi,

I had the same bug too. You can find a pull request https://github.com/cleentfaar/slack/pull/22 to make it work.

Antoine

**Comment by inmarelibero** [comment]
experiencing this issue too, has the PR been rejected?

**Comment by titouan13** [comment]
No I don't have time to update tests as well so it won't pass tests.
This is the commit I am using to make it work:
https://github.com/titouan13/slack/commit/582dfeb73c09a02ce6b6c3382fbd029532e9818f

I will try to make a PR in July

**Comment by inmarelibero** [comment]
ok cool, thanks!

**Comment by cleentfaar** [comment]
Sorry for the (very) late reply. This should be resolved by now (release 0.18.1: https://github.com/cleentfaar/CLSlackBundle/releases/tag/0.18.1), please re-open if there are further issues.
