### ISSUE TITLE
Issue with guzzlehttp version: ConnectException: cURL error 6: Could not resolve host: POST

### ISSUE THREAD

**Issue by hugomn** [cleentfaar/CLSlackBundle#15]
Slack-bundle versions 0.15.4 and 0.15.1 is raising erros in guzzlehttp->createRequest error due to guzzlehttp version. Looks like guzzlehttp has new versions and its not locked in slack-bundle composer.json. Possible solutions:

1) Change slack-bundle ApiClient.php:createRequest method to use new guzzlehttp structure (not sure how to do it. If someone points me to the right direction, I can create a PR).

2) Force slack-bundle to use version 4.2.3 of guzzlehttp.

I've just added "guzzlehttp/guzzle": "4.2.3", in my composer.json and it's working fine now. 

Thanks!

**Comment by ryzy** [comment]
The reason is that this bundle requires old version of `cleentfaar/slack`.

For now the quickest workaround is to add the following line to your composer.json:
```
"cleentfaar/slack": "0.18.1 as 0.15.3",
```

**Comment by tubersan** [comment]
I didn't have any luck with `cleentfaar/slack 0.18.1`, since it required `jms/serializer ~1.0` while `cleentfaar/slack-bundle 0.15.4` required `jms/serializer 0.16`.

What did work was using `cleentfaar/slack 0.17.1`, which still required `jms/serializer 0.16`.
So I added
```
"cleentfaar/slack": "0.17.1 as 0.15.3",
```
to my composer.json and ran
```
composer update cleentfaar/slack
```

**Comment by LeoBenoist** [comment]
The solution is great but the bundle is not completely compatible with the library anymore causing the test function to crash !

**Comment by cleentfaar** [comment]
Sorry for the late reply, this should be resolved by the latest release: https://github.com/cleentfaar/CLSlackBundle/releases/tag/0.18.1. If any problems remain, please create a separate issue

**Comment by LeoBenoist** [comment]
Thanks :)
